const actionsArray = [
"Fais une pyramide de cartes. Si ça ne marche pas, tu bois deux fois.",
"Tiens sur une jambe pendant 2 minutes",
"Fais le pont",
"Retiens ta respiration jusqu’à être tout rouge",
"Fais un concours de gainage. Si tu perds, tu bois X2",
"Fais une démonstration à fond de 2 minutes d’Air sexe",
"Donne-toi à fond dans ta position préférée",
"Fais un équilibre",
"Fais la chaise pendant 2 minutes contre un mur",
"Fais des pompes",
"Fais des abdos",
"Fais des squats en tournant les fesses vers ton public",
"Fais un gainage en épluchant un oignon avec les yeux écarquillés",
"Entame un twerk sur un des participants",
"Fais un striptease sur « sexual healing » ou « let’s get it on »",
"Fais la danse du ventre",
"Fais une chorégraphie sur Aya Nakamura",
"Met du liquide vaisselle dans tes cheveux",
"Fais-toi brûler des poils",
"Epile-toi les poils de nez. Si tu n’en as pas, tu es chanceux",
"Fais-toi une bande épilatoire sur la jambe ou le torse. Sinon, un trait de rasoir dans le sourcil",
"Lave tes cheveux avec du lait, de l’huile ou du vinaigre",
"Fais un poème d’amour à quelqu’un dans la salle",
"Ecris un message d’amour à quelqu’un que tu n’aimes pas",
"Attache les lacets de tes chaussures ensemble pendant trois tours",
"Fais-toi attacher les mains derrière le dos pendant trois tours",
"Fais-toi dessiner sur le front et tu n’as pas le droit d’effacer.",
"Mets les lunettes de quelqu’un d’autre pendant un tour. La correction doit être différente de la tienne.",
"Tes potes te maquillent à leur guise. Garde le résultat pendant 3 tours",
"Ecoute « J’aime les licornes » pendant 1 tour avec des écouteurs",
"Désormais, tu t’appelles Gérard. Tous ceux qui t’appellent autrement que Gérard boivent Si tu t’appelles déjà Gérard, tant pis, tu as un prénom de vieux",
"Prétends que tu as changé d’orientation sexuelle pendant une semaine",
"Interdiction de pisser pendant 30 minutes",
"Met ton pantalon à l’envers",
"Echange un habit avec quelqu’un du sexe opposé",
"Mets une de tes chaussettes en bouche",
"Nettoie tes chaussures avec une brosse de toilettes",
"Mets une capote sur ta tête",
"Mets-toi en sous-vêtements et reste comme ca jusqu’au prochain tour",
"Raconte ta blague la plus nulle.",
"Imagine un scénario de films pour adulte",
"Fais rire les autres. Sinon tu bois deux fois",
"Invente un rap de 5 phrases",
"Chante une parodie (par exemple Sébastien Patoche)",
"« Massacre » une chanson de ton choix",
"Sois gênant pendant 5 minutes",
"Chante une chanson très sentimentale à fond",
"Fais une démonstration de pipe ou cunni. Les autres te donnent une note sur 5. Tu bois la différence",
"Avoue quelque chose dont tu as honte",
"Mets-toi de l’eau au niveau de l’entrejambe",
"Fais un tour tout nu dans le jardin. Si c’est une cour ou la rue, protège ton sexe",
"Fais un bisou sur les pieds d’un des participants",
"Renifle le derrière de la dernière personne qui est allé aux toilettes",
"Mets-toi à la fenêtre et crie un message politique 3 fois",
"Mets une photo X en fond d’écran de portable ou ordinateur pendant une semaine",
"Mets une vidéo d’animaux qui baisent avec le son à fond pendant un tour",
"Appelle tes parents en faisant croire que tu es au commissariat ou que tu as eu un accident avec la voiture parce que tu es bourré",
"Prête ton portable pour qu’on renomme tes contacts",
"Envoie un message gênant à un de tes parents",
"Mets une photo laide de toi en story pendant une journée",
"Partage la page de Zemmour sur Instagram, Twitter ou Facebook",
"Partage ce jeu sur un réseau social",
"Envoie un message de désespoir à ton ex",
"Fais confiance à tes potes et mange à l’aveugle une de leurs créations",
"Mange un citron entier",
"Mange un demi oignon entier",
"Mange une gousse d’ail",
"Brosse-toi les dents avec du savon",
"Bois un verre d’eau chaude",
"Bois un shot d’huile",
"Gobe un œuf. S’il n’y a pas d’œufs, tu bois",
"Avale une cuiller à café de cannelle",
"Avale une cuiller à café de piment",
"Mange une banane entière d’un coup",
"Passe ta main sous tes aisselles et lèche-la",
"Mange une pomme de terre crue",
"Mange un fruit assaisonné aux sel, poivre et piment",
"Mange un peu de gros sel",
"Mange un toast brûlé",
"Broute de l’herbe. S’il n’y a pas d’herbe à disposition, tu t’en sors bien",
"Mange un aliment que tu n’aimes pas. Les autres le choisissent",
"Casse un œuf à une main (si tu ne réussis pas, sur le front). S’il n’y a plus d’œufs, tu bois X2.",
"Ferme les yeux pendant un tour",
"Ecris « I love Trump » sur ton front",
"Fais des prouts avec ton genou ou ton oreille",
"Fais un pet enflammé avec un briquet. Tu as 3 tours pour y arriver",
"Mets-toi au milieu du cercle et laisse-toi insulter pendant 1 minute",
"Laisse deux autres te mettre chacun un doigt mouillé dans une oreille simultanément",
"Tout le monde te met une fessée",
"Tu subis un tire-slip",
"Prends une douche glacée",
"Sniffe du piment ou du poivre",
"Verse du citron dans une de tes plaies. Si tu n’en as pas, tu t’en sors bien",
"Prends-toi un coup dans l’entrejambes",
"Prends-toi un pince-têton",
"Prends-toi un suçon",
"Mime quelqu’un de ton choix",
"Mime quelqu’un de ton public",
"Mime un prof",
"Mime une célébrité ou une personne politique",
"Parle bien mal de quelqu’un de ton choix pendant 1 minute (moins c'est réussi, plus tu bois",
];

export default actionsArray;