const questionsArray = [
"De qui es-tu amoureux ?",
"Si tu devais sortir avec quelqu’un de ce groupe, ça serait qui ?",
"Qui était la première personne que tu as embrassée et quand ?",
"As-tu déjà trompé ton partenaire ?",
"Avec quelle célébrité aimerais-tu sortir ?",
"Nomme deux personnes qui tu détestes et dis pourquoi.",
"Nomme la personne que tu aimes le moins dans la salle.",
"Quelle personnalité politique aimerais-tu voir mourir (hors Trump) ?",
"Assume un de tes complexes.",
"Quand est-ce que tu t’es chié dessus pour la dernière fois ?",
"Quand est-ce que tu t’es pissé dessus pour la dernière fois ?",
"Quand est-ce que tu t’es vomi dessus pour la dernière fois ?",
"As-tu déjà vu tes parents baiser ?",
"Quelle est la pire recal ou bûche que tu t’es pris ?",
"A quand remonte ta dernière excitation en public ?",
"Quelle est la vidéo porno que tu as regardé dont tu as le plus honte ?",
"As-tu déjà été victime d’une fraude invraisemblable ?",
"As-tu déjà agressé quelqu’un sans raison ?",
"Quel est le plus grand nombre de gens que tu aies contaminé avec une seule maladie ?",
"As-tu déjà contaminé des gens avec une maladie en soirée ? Combien et avec quelle maladie ?",
"Quel est l’objet le plus gênant que tu possèdes ?",
"As-tu déjà pris du viagra ?",
"Mangeais-tu tes crottes de nez petit ?",
"As-tu déjà rogné tes ongles d’orteils ?",
"Quel est le truc le plus gênant que tu aies dit à quelqu’un ?",
"Quel est le plus gros montant d’argent que tu aies perdu ?",
"Quel est le plus gros pari que tu aies perdu ?",
"T’es-tu tapé avec quelqu’un bourré ?",
"Quel est le truc le plus dégoutant que tu aies fait dans ton lit ?",
"As-tu déjà vomi sur quelqu’un ?",
"As-tu déjà été enceinte ou mis quelqu’un enceinte par accident ?",
"Es-tu déjà allé dans un sexshop ou un cinéma érotique ?",
"T’es-tu déjà fait viré de boîte ?",
"Quel est ton fantasme ?",
"Quel animal choisirais-tu comme partenaire ?",
"As-tu déjà fantasmé sur quelqu’un du groupe ?",
"As-tu déjà fantasmé sur un des parents d’un(e) pote ?",
"Quelle est ton acteur/ actrice x favori(te) ?",
"As-tu déjà testé la sodomie ?",
"Quelle est ta catégorie porno préférée ?",
"Quelle est ta position sexuelle préférée ?",
"Quel est le clip de musique le plus sexy selon toi ?",
"Quel est ton site porno préféré ?",
"Quel est ton critère favori pour évaluer quelqu’un physiquement ?",
"As-tu déjà fantasmé sur quelqu’un du même sexe (ou du sexe opposé si tu es gay) ?",
"As-tu déjà utilisé un sextoy ?",
"As-tu déjà été excité par un animal ?",
"Quel est ta partie préférée du sexe que tu convoites ?",
"Si tu devais coucher avec une personnalité politique, ça serait qui ?",
"As-tu déjà maté ton voisin/ ta voisine ?",
"As-tu déjà fantasmé sur un héro de BD ou de dessin animé ?",
"Es-tu déjà entré par quelque part par effraction ?",
"As-tu déjà mis le feu quelque part ?",
"As-tu déjà uriné dans un transport en commun ?",
"As-tu déjà vomi dans un transport en commun ?",
"As-tu déjà vomi dans un taxi ?",
"As-tu déjà pris des drogues sans le faire exprès ?",
"As-tu déjà sniffé de la colle ?",
"Quand as-tu été le plus défoncé ?",
"As-tu déjà vandalisé une voiture ?",
"As-tu déjà vandalisé une du verre (vitrine, fenêtre, vitre…) ?",
"Quelle était ta pire honte de soirée ?",
"Quelle était ta pire bêtise ?",
"Quel était ton pire exploit culinaire ?",
"Quel était ton pire souvenir laissé par un prof ?",
"Quelle était la pire punition de tes parents ?",
"Quelle était ta pire expérience en tuant un animal ?",
"Quelle était la pire manière dont tu as cassé ton portable ?",
"Quelle est ta pire expérience de diarrhée ?",
"Quel est le pire cadeau que tu aies fait ?",
"Quel est le pire cadeau qu’on t’aie fait ?",
"Quelle était la pire baise ou branlette de ta vie ?",
"Quelle était ta pire expérience en faisant du sport ?",
"Quelle était ta pire expérience avec un ballon ?",
"Quelle était ta pire expérience avec un ordinateur ?",
"Quelle était ta pire expérience avec un arbre ?",
"Quelle était ta pire chute ?",
"Quel était ton pire bad trip ?",
"Quelle est la pire douleur que tu aies ressenti ?",
"Quelle a été ta pire indigestion ?",
"Quelle a été ta pire expérience avec une poubelle ?",
"Quelle a été ta pire humiliation par un prof ?",
"Quelle a été ta pire humiliation à l’école ?",
"Quelle est la pire fois où tu a été une bonne grosse merde ?",
"Quelle est le pire truc que tu aies fait à un voisin ?",
"Quelle est ta pire histoire d’arnaque ?",
"Quelle était ta pire frayeur causée par un animal ?",
"Quelle était ta pire frayeur causée par quelqu’un de bourré ou drogué ?",
"Quelle était ta pire frayeur causée par tes parents ?",
"Quelle était ta pire frayeur sur internet ?",
"Quelle a été ta pire frayeur à l’école ?",
"Quelle a été ta pire frayeur à la piscine ?",
"Quelle a été ta pire frayeur à la mer ?",
"Que feras-tu si tu gagnes au Loto ?",
"Quel est ton rêve dans la vie ?",
"En quel animal veux-tu te réincarner ?",
"Qui voudrais-tu ressusciter ?",
"Es-tu puceau ?",
"Quand était ta première masturbation ?",
"Quel est ton poids ?",
"Quelle est ta taille de poitrine/ la taille de poitrine idéale d’une partenaire ?",
"Quelle est ta taille de pénis/ la taille de pénis idéale d’un partenaire ?",
"Es-tu satisfait de ta taille de pénis/ de poitrine et pourquoi ?",
"Quelle est ta marque de capote préférée ? Pourquoi ?",
"As-tu ou as-tu eu un compte sur un site de rencontre ?",
"As-tu conclu avec quelqu’un sur un site de rencontre ?",
"As-tu déjà envoyé des nudes ?",
"As-tu déjà reçu des nudes ?",
"Quelle est ta plus grande peur ?",
"As-tu déjà masturbé dans un avion ou un train ?",
"Combien de fois par jour/ par semaine masturbes-tu ?",
"Quel est le truc le plus cruel que tu aies fait petit ?",
"Quel est le truc le plus idiot que tu aies fait petit ?",
"As-tu déjà pris des drogues et baisé ?",
"Te ronges-tu les ongles ?",
"Est-ce que faire caca est un plaisir pour toi ?",
"As-tu déjà pensé au suicide ?",
"Est-ce que tu te rases le maillot ?",
"As-tu déjà eu une infection urinaire ?",
"As-tu une MST en ce moment ?",
"As-tu déjà eu une relation sexuelle dans un endroit publique ?",
"Est-ce que ça te gêne de faire pipi en public ?",
"Est-ce que ça te gêne de faire caca en public ?",
"Quel animal serais-tu ?",
"Quelle est ta boisson préférée en soirée ?",
"Quel est ton personnage préféré de télé réalité ?",
"Quelle est la bouffe la plus exotique que tu aies jamais mangé ?",
"Quel est l’objet le plus cher que tu aies perdu ?",
"As-tu déjà eu un accident de voiture ?",
"As-tu déjà eu un accident de vélo ?",
"Quel est le plus beau cadeau que tu aies fait ?",
"As-tu déjà risqué ta vie ?",
"Quelle est ton équipe de foot préférée ?",
"Quel est ton artiste préféré ?",
"Quelle est ta drogue préférée ?",
"T’es-tu déjà cassé quelque-chose ?",
"Quand as-tu été le plus bourré ?",
"Quel est le plus gros pari que tu aies fait ?",
"Donne une estimation de ton record d’alcoolémie.",
"As-tu un super-pouvoir ?",
"En quel animal mérites-tu de te réincarner ?",
"Es-tu plutôt écouteurs ou casque ?",
"Pour combien te ferais-tu enculer (maximum 100,000€ ?) ?",
"Quel est le plus gros bruit que tu aies fait ?",
"Qu’as-tu bu la fois où tu étais le plus bourré ?",
"As-tu déjà pissé sur une barrière électrique ?",
"As-tu déjà craché sur quelqu’un ?",
"Quelle est la meilleure fois où tu as été une bonne grosse merde ?",
"Es-tu pour ou contre la sodomie ?",
"Es-tu pour ou contre l’avortement ?",
"Es-tu pour ou contre l’égalité des sexes ?",
"Es-tu pour ou contre la GPA ?",
"Quelle est ta vision du mariage ?",
"Es-tu pour ou contre les théories conspirationnistes ? Lesquelles ?",
"Es-tu pour ou contre le port du voile ?",
"Es-tu pour ou contre le mariage gay ?",
"Es-tu pour ou contre les véganes ?",
"Est-ce que la vierge Marie est vierge ?",
"Le colonialisme en Afrique a-t-il aidé ces pays ?",
"Est-ce que les filles complètement épilées, ça se rapproche de la pédophilie ?",
"Est-ce que l’eau a un goût ?",
"Que penses-tu des non-binaires ?",
"Que penses-tu du Bitcoin ?",
"Qui est le plus gros mytho parmi vous ?",
"Qui est le plus beau parmi vous ?",
"Qui est le plus moche parmi vous ?",
"Qui est le plus con parmi vous ?",
"Qui est le plus chiant parmi vous ?",
"Qui est le plus brillant parmi vous ?",
"Qui est le plus drôle parmi vous ?",
"Qui est le plus collant parmi vous ?",
"Qui est le plus virile parmi vous ?",
"Qui est le plus féminin parmi vous ?",
"Qui est le plus radin parmi vous ?",
"Qui pues le plus de la gueule parmi vous ?",
"Qui pues le plus parmi vous ?",
"Qui est le plus sale parmi vous ?",
"Qui a les plus beaux yeux parmi vous ?",
"Qui est le meilleur coup parmi vous ?",
"Qui a les pieds les plus moches parmi vous ?",
"Qui est le plus coincé parmi vous ?",
"Qui serait le meilleur colloc ?",
"Qui serait le pire colloc ?",
"Qui d’entre vous a la pire coiffure ?",
"Qui a le pire goût vestimentaire ?",
"Qui a le meilleur goût vestimentaire ?",
"As-tu menti pendant ce jeux ?",
];

export default questionsArray;